import Mathlib
import RequestProject.TickDualMapping

/-!
# Open-loop control layer for the realized-volatility forge cron

This module supplies the **base control layer** requested in the
`Control layer (requirements)` section of `REALIZED_VOLATILITY.md`, continuing from
`RequestProject/TickDualMapping.lean` (where `g (i) = exp (β i)`, `σ (i) = exp (α - β i)` and the
terminal tick `i (N) = (α - ln σ̄) / β` were established).

## What is formalised

* **The recursion** (`tickRec`).  A diffusion-shaped Euler scheme for the tick,
  `i j = i (j-1) + κ · D (i (j-1)) + S (i (j-1)) · ε j`,
  where `D` is the drift increment `(d̄t / β) · μ (·)` of the md SDE, `S` is the diffusion
  increment `σ (·) · √d̄t`, and `{ε j}` is an **exogenous** shock stream (the Solidity
  `keccak (seed, blockhash, j)` PRNG output).  The shocks are never solved for: every statement
  below is "for an arbitrary fixed `ε`".
* **The one-parameter drift family.**  Only the scalar `κ` multiplies the drift, so the diffusion
  coefficient — the `σ (i)` profile of the model — is untouched (`tickRec_diffusion_profile`,
  `modelRec_succ`).
* **Existence of `κ⋆`** (`exists_kappa_of_bounds`, `exists_kappa_model`): for any fixed shock
  stream, a drift scale `κ⋆` hitting the terminal tick exactly exists; it is obtained from the
  intermediate value theorem applied to the (continuous) endpoint map `κ ↦ i N (κ)`, together with
  explicit two-sided brackets `kL ≤ κ⋆ ≤ kU` computed from the shock stream
  (`kappaLower`, `kappaUpper`).
* **Uniqueness of `κ⋆`** (`tickRec_endpoint_strictMono`, `kappa_unique`) under the stated
  step-monotonicity hypothesis (a step-size condition: each Euler step is nondecreasing in the
  state) and strict positivity of the drift.
* **The realized path** (`forgePath`) and the fact that it realizes the target volatility:
  `σ (i N) = σ̄` (`forgePath_vol_terminal`), with the profile `σ (i j) = exp (α - β i j)` at every
  node (`forgePath_vol`).

## Forge evaluation order (consumer)

The cron script evaluates in exactly this order — see `forgeEvaluationOrder`:

1. **obtain `ε`** — reveal the sealed seed, xor with the future blockhash, expand to
   `{ε j}` by the PRNG; from this point the stream is a fixed, known sequence;
2. **solve `κ⋆`** — `kappaStar`, the drift scale pinning `i N = (α - ln σ̄) / β`
   (bracketed by `kappaLower`/`kappaUpper`, hence solvable by bisection on chain-off scripts);
3. **emit `{i j}`** — run `forgePath` forward and write the resulting `TickHistory`.

Out of scope here (as per the spec): the commit–reveal protocol, gas batching, and the concrete
`TickState` / factory types.
-/

namespace TickControlLayer

open Real

/-! ## Part 1: the abstract driven recursion

`D` is the (state dependent) drift increment, `S` the (state dependent) diffusion increment and
`ε` the exogenous shock stream.  Nothing in this part uses the specific model shapes, so the
results apply verbatim to the md coefficients of Part 2. -/

/-- The open-loop tick recursion `i j = i (j-1) + κ · D (i (j-1)) + S (i (j-1)) · ε j`.
The single scalar `κ` scales the drift only; the diffusion coefficient `S` is untouched. -/
def tickRec (D S : ℝ → ℝ) (ε : ℕ → ℝ) (i0 κ : ℝ) : ℕ → ℝ
  | 0 => i0
  | (j + 1) =>
      let x := tickRec D S ε i0 κ j
      x + κ * D x + S x * ε (j + 1)

@[simp] theorem tickRec_zero (D S : ℝ → ℝ) (ε : ℕ → ℝ) (i0 κ : ℝ) :
    tickRec D S ε i0 κ 0 = i0 := rfl

theorem tickRec_succ (D S : ℝ → ℝ) (ε : ℕ → ℝ) (i0 κ : ℝ) (j : ℕ) :
    tickRec D S ε i0 κ (j + 1) =
      tickRec D S ε i0 κ j + κ * D (tickRec D S ε i0 κ j)
        + S (tickRec D S ε i0 κ j) * ε (j + 1) := rfl

/-- **The `σ`-profile is preserved.**  The coefficient multiplying the shock at step `j + 1` is
`S` evaluated at the lagged state, whatever the drift scale `κ` is: tuning `κ` never rescales the
diffusion coefficient. -/
theorem tickRec_diffusion_profile (D S : ℝ → ℝ) (ε : ℕ → ℝ) (i0 κ : ℝ) (j : ℕ) :
    tickRec D S ε i0 κ (j + 1) - tickRec D S ε i0 κ j
        - κ * D (tickRec D S ε i0 κ j)
      = S (tickRec D S ε i0 κ j) * ε (j + 1) := by
  rw [tickRec_succ]; ring

/-- Every node of the path is a well-defined real number, and the path is exactly the one
generated by the recursion: this is the defining characterisation. -/
theorem tickRec_unique_path (D S : ℝ → ℝ) (ε : ℕ → ℝ) (i0 κ : ℝ) (f : ℕ → ℝ)
    (h0 : f 0 = i0) (hstep : ∀ j, f (j + 1) = f j + κ * D (f j) + S (f j) * ε (j + 1)) :
    ∀ n, f n = tickRec D S ε i0 κ n := by
  intro n
  induction n with
  | zero => simp [h0]
  | succ n ih => rw [hstep n, tickRec_succ, ih]

/-- The endpoint map `κ ↦ i n (κ)` is continuous. -/
theorem tickRec_continuous {D S : ℝ → ℝ} (hD : Continuous D) (hS : Continuous S)
    (ε : ℕ → ℝ) (i0 : ℝ) (n : ℕ) : Continuous fun κ : ℝ => tickRec D S ε i0 κ n := by
  induction n with
  | zero => simpa using continuous_const
  | succ n ih =>
      simp only [tickRec_succ]
      exact ((ih.add (continuous_id.mul (hD.comp ih))).add
        (((hS.comp ih)).mul continuous_const))

/-- Cumulated absolute shock size over the first `n` steps. -/
noncomputable def shockMass (ε : ℕ → ℝ) (n : ℕ) : ℝ := ∑ j ∈ Finset.range n, |ε (j + 1)|

theorem shockMass_nonneg (ε : ℕ → ℝ) (n : ℕ) : 0 ≤ shockMass ε n :=
  Finset.sum_nonneg fun _ _ => abs_nonneg _

/-- For a nonnegative drift scale the path is bounded below by a line in `κ`. -/
theorem tickRec_lower_bound {D S : ℝ → ℝ} {d₀ Sm κ : ℝ} (ε : ℕ → ℝ) (i0 : ℝ)
    (hd : ∀ x, d₀ ≤ D x) (hS : ∀ x, |S x| ≤ Sm) (hκ : 0 ≤ κ) (n : ℕ) :
    i0 + n * κ * d₀ - Sm * shockMass ε n ≤ tickRec D S ε i0 κ n := by
  induction n with
  | zero => simp [shockMass]
  | succ n ih =>
      have hx := hd (tickRec D S ε i0 κ n)
      have hκd : κ * d₀ ≤ κ * D (tickRec D S ε i0 κ n) := by
        exact mul_le_mul_of_nonneg_left hx hκ
      have hnoise : -(Sm * |ε (n + 1)|) ≤ S (tickRec D S ε i0 κ n) * ε (n + 1) := by
        have h1 : |S (tickRec D S ε i0 κ n) * ε (n + 1)| ≤ Sm * |ε (n + 1)| := by
          rw [abs_mul]
          exact mul_le_mul_of_nonneg_right (hS _) (abs_nonneg _)
        have := abs_le.1 h1
        exact this.1
      have hsum : shockMass ε (n + 1) = shockMass ε n + |ε (n + 1)| := by
        simp [shockMass, Finset.sum_range_succ]
      rw [tickRec_succ, hsum]
      push_cast
      nlinarith [ih]

/-- For a nonpositive drift scale the path is bounded above by a line in `κ`. -/
theorem tickRec_upper_bound {D S : ℝ → ℝ} {d₀ Sm κ : ℝ} (ε : ℕ → ℝ) (i0 : ℝ)
    (hd : ∀ x, d₀ ≤ D x) (hS : ∀ x, |S x| ≤ Sm) (hκ : κ ≤ 0) (n : ℕ) :
    tickRec D S ε i0 κ n ≤ i0 + n * κ * d₀ + Sm * shockMass ε n := by
  induction n with
  | zero => simp [shockMass]
  | succ n ih =>
      have hx := hd (tickRec D S ε i0 κ n)
      have hκd : κ * D (tickRec D S ε i0 κ n) ≤ κ * d₀ := by
        exact mul_le_mul_of_nonpos_left hx hκ
      have hnoise : S (tickRec D S ε i0 κ n) * ε (n + 1) ≤ Sm * |ε (n + 1)| := by
        have h1 : |S (tickRec D S ε i0 κ n) * ε (n + 1)| ≤ Sm * |ε (n + 1)| := by
          rw [abs_mul]
          exact mul_le_mul_of_nonneg_right (hS _) (abs_nonneg _)
        exact (abs_le.1 h1).2
      have hsum : shockMass ε (n + 1) = shockMass ε n + |ε (n + 1)| := by
        simp [shockMass, Finset.sum_range_succ]
      rw [tickRec_succ, hsum]
      push_cast
      nlinarith [ih]

/-- Explicit lower bracket for the drift scale. -/
noncomputable def kappaLower (ε : ℕ → ℝ) (i0 iT d₀ Sm : ℝ) (N : ℕ) : ℝ :=
  min 0 ((iT - i0 - Sm * shockMass ε N) / (N * d₀))

/-- Explicit upper bracket for the drift scale. -/
noncomputable def kappaUpper (ε : ℕ → ℝ) (i0 iT d₀ Sm : ℝ) (N : ℕ) : ℝ :=
  max 0 ((iT - i0 + Sm * shockMass ε N) / (N * d₀))

theorem kappaLower_le_kappaUpper (ε : ℕ → ℝ) (i0 iT d₀ Sm : ℝ) (N : ℕ) :
    kappaLower ε i0 iT d₀ Sm N ≤ kappaUpper ε i0 iT d₀ Sm N :=
  le_trans (min_le_left _ _) (le_max_left _ _)

/-- **Existence of the drift scale `κ⋆` (abstract form).**
For *any* fixed shock stream `ε`, provided the drift increment is bounded below by a positive
constant and the diffusion increment is bounded, there is a drift scale inside the explicit
bracket `[kappaLower, kappaUpper]` whose path hits the prescribed terminal tick exactly. -/
theorem exists_kappa_of_bounds {D S : ℝ → ℝ} {d₀ Sm : ℝ} (ε : ℕ → ℝ) (i0 iT : ℝ) {N : ℕ}
    (hD : Continuous D) (hS : Continuous S) (hd₀ : 0 < d₀) (hd : ∀ x, d₀ ≤ D x)
    (hSb : ∀ x, |S x| ≤ Sm) (hN : 0 < N) :
    ∃ κ ∈ Set.Icc (kappaLower ε i0 iT d₀ Sm N) (kappaUpper ε i0 iT d₀ Sm N),
      tickRec D S ε i0 κ N = iT := by
  set B := Sm * shockMass ε N with hB
  set kL := kappaLower ε i0 iT d₀ Sm N with hkL
  set kU := kappaUpper ε i0 iT d₀ Sm N with hkU
  have hNpos : (0 : ℝ) < (N : ℝ) := by exact_mod_cast hN
  have hNd : (0 : ℝ) < (N : ℝ) * d₀ := mul_pos hNpos hd₀
  have hSm : 0 ≤ Sm := le_trans (abs_nonneg (S 0)) (hSb 0)
  have hBnonneg : 0 ≤ B := mul_nonneg hSm (shockMass_nonneg ε N)
  -- upper end: the endpoint at `kU` is at least the target
  have hupper : iT ≤ tickRec D S ε i0 kU N := by
    have hkU0 : 0 ≤ kU := le_max_left _ _
    have hlow := tickRec_lower_bound (D := D) (S := S) (d₀ := d₀) (Sm := Sm) ε i0 hd hSb hkU0 N
    have key : iT ≤ i0 + (N : ℝ) * kU * d₀ - B := by
      rcases le_or_gt ((iT - i0 + B) / ((N : ℝ) * d₀)) 0 with h | h
      · have hkUeq : kU = 0 := by
          rw [hkU, kappaUpper]
          exact max_eq_left h
        have : iT - i0 + B ≤ 0 := by
          by_contra hc
          push_neg at hc
          have : 0 < (iT - i0 + B) / ((N : ℝ) * d₀) := div_pos hc hNd
          linarith
        rw [hkUeq]; nlinarith
      · have hkUeq : kU = (iT - i0 + B) / ((N : ℝ) * d₀) := by
          rw [hkU, kappaUpper]
          exact max_eq_right (le_of_lt h)
        rw [hkUeq]
        have : (N : ℝ) * ((iT - i0 + B) / ((N : ℝ) * d₀)) * d₀ = iT - i0 + B := by
          field_simp
        rw [this]; ring_nf; nlinarith
    linarith
  -- lower end: the endpoint at `kL` is at most the target
  have hlower : tickRec D S ε i0 kL N ≤ iT := by
    have hkL0 : kL ≤ 0 := min_le_left _ _
    have hup := tickRec_upper_bound (D := D) (S := S) (d₀ := d₀) (Sm := Sm) ε i0 hd hSb hkL0 N
    have key : i0 + (N : ℝ) * kL * d₀ + B ≤ iT := by
      rcases le_or_gt 0 ((iT - i0 - B) / ((N : ℝ) * d₀)) with h | h
      · have hkLeq : kL = 0 := by
          rw [hkL, kappaLower]
          exact min_eq_left h
        have : 0 ≤ iT - i0 - B := by
          by_contra hc
          push_neg at hc
          have : (iT - i0 - B) / ((N : ℝ) * d₀) < 0 := div_neg_of_neg_of_pos hc hNd
          linarith
        rw [hkLeq]; nlinarith
      · have hkLeq : kL = (iT - i0 - B) / ((N : ℝ) * d₀) := by
          rw [hkL, kappaLower]
          exact min_eq_right (le_of_lt h)
        rw [hkLeq]
        have : (N : ℝ) * ((iT - i0 - B) / ((N : ℝ) * d₀)) * d₀ = iT - i0 - B := by
          field_simp
        rw [this]; ring_nf; nlinarith
    linarith
  have hcont : ContinuousOn (fun κ : ℝ => tickRec D S ε i0 κ N) (Set.Icc kL kU) :=
    (tickRec_continuous hD hS ε i0 N).continuousOn
  have hle : kL ≤ kU := kappaLower_le_kappaUpper ε i0 iT d₀ Sm N
  have hmem : iT ∈ Set.Icc (tickRec D S ε i0 kL N) (tickRec D S ε i0 kU N) := ⟨hlower, hupper⟩
  obtain ⟨κ, hκmem, hκ⟩ := intermediate_value_Icc hle hcont hmem
  exact ⟨κ, hκmem, hκ⟩

/-! ### Uniqueness of the drift scale -/

/-- Under a step-size condition (each Euler step is nondecreasing in the state) and strict
positivity of the drift increment, the endpoint map `κ ↦ i n (κ)` is strictly increasing. -/
theorem tickRec_endpoint_strictMono {D S : ℝ → ℝ} (ε : ℕ → ℝ) (i0 : ℝ)
    (hpos : ∀ x, 0 < D x)
    (hstep : ∀ (κ : ℝ) (j : ℕ), Monotone fun x : ℝ => x + κ * D x + S x * ε j)
    {n : ℕ} (hn : 0 < n) : StrictMono fun κ : ℝ => tickRec D S ε i0 κ n := by
  -- first prove monotone (weak) for all `n`, then strict for `n ≥ 1`
  have weak : ∀ m : ℕ, Monotone fun κ : ℝ => tickRec D S ε i0 κ m := by
    intro m
    induction m with
    | zero => intro a b _; simp
    | succ m ih =>
        intro a b hab
        have h1 : tickRec D S ε i0 a m ≤ tickRec D S ε i0 b m := ih hab
        have h2 : tickRec D S ε i0 a (m + 1)
            ≤ tickRec D S ε i0 b m + a * D (tickRec D S ε i0 b m)
              + S (tickRec D S ε i0 b m) * ε (m + 1) := by
          rw [tickRec_succ]
          exact hstep a (m + 1) h1
        have h3 : a * D (tickRec D S ε i0 b m) ≤ b * D (tickRec D S ε i0 b m) :=
          mul_le_mul_of_nonneg_right hab (le_of_lt (hpos _))
        show tickRec D S ε i0 a (m + 1) ≤ tickRec D S ε i0 b (m + 1)
        rw [tickRec_succ (κ := b)]
        linarith
  intro a b hab
  obtain ⟨m, rfl⟩ : ∃ m, n = m + 1 := ⟨n - 1, by omega⟩
  have h1 : tickRec D S ε i0 a m ≤ tickRec D S ε i0 b m := weak m (le_of_lt hab)
  have h2 : tickRec D S ε i0 a (m + 1)
      ≤ tickRec D S ε i0 b m + a * D (tickRec D S ε i0 b m)
        + S (tickRec D S ε i0 b m) * ε (m + 1) := by
    rw [tickRec_succ]
    exact hstep a (m + 1) h1
  have h3 : a * D (tickRec D S ε i0 b m) < b * D (tickRec D S ε i0 b m) :=
    mul_lt_mul_of_pos_right hab (hpos _)
  show tickRec D S ε i0 a (m + 1) < tickRec D S ε i0 b (m + 1)
  rw [tickRec_succ (κ := b)]
  linarith

/-- **Uniqueness of `κ⋆`.**  Under the same hypotheses, at most one drift scale reaches a given
terminal tick, so the `κ⋆` produced by `exists_kappa_of_bounds` is *the* drift scale. -/
theorem kappa_unique {D S : ℝ → ℝ} (ε : ℕ → ℝ) (i0 iT : ℝ)
    (hpos : ∀ x, 0 < D x)
    (hstep : ∀ (κ : ℝ) (j : ℕ), Monotone fun x : ℝ => x + κ * D x + S x * ε j)
    {N : ℕ} (hN : 0 < N) {κ₁ κ₂ : ℝ}
    (h₁ : tickRec D S ε i0 κ₁ N = iT) (h₂ : tickRec D S ε i0 κ₂ N = iT) : κ₁ = κ₂ :=
  (tickRec_endpoint_strictMono ε i0 hpos hstep hN).injective (by simp [h₁, h₂])

/-! ## Part 2: the model coefficients from `REALIZED_VOLATILITY.md`

Recall `√p (i) = exp (β i)`, `σ (i) = exp (α - β i)` with `α = ln (σ_F / (L ln 1.0001))` and
`β = ln 1.0001`, and

`μ (i) = μ_F / (L √p (i)) - σ_F² / (2 L² p (i))`,
`Δ i = (d̄t / β) μ (i) + σ (i) ΔW`,  `ΔW = √d̄t · ε`.

The drift increment is `tickDrift` and the diffusion increment `tickDiff`; the control scales the
former only. -/

/-- The md drift `μ (i) = μ_F / (L √p) - σ_F² / (2 L² p)` written in the tick, using
`√p (i) = exp (β i)`. -/
noncomputable def modelMu (β muF sigF Lhalf : ℝ) (i : ℝ) : ℝ :=
  muF / Lhalf * exp (-(β * i)) - sigF ^ 2 / (2 * Lhalf ^ 2) * exp (-(β * i)) ^ 2

/-- The drift increment of the tick recursion: `(d̄t / β) · μ (i)`. -/
noncomputable def tickDrift (β dt muF sigF Lhalf : ℝ) (i : ℝ) : ℝ :=
  dt / β * modelMu β muF sigF Lhalf i

/-- The diffusion increment of the tick recursion: `σ (i) · √d̄t`, with
`σ (i) = exp (α - β i)` — the volatility profile of the model. -/
noncomputable def tickDiff (α β dt : ℝ) (i : ℝ) : ℝ :=
  TickDualMapping.vol α β i * Real.sqrt dt

theorem tickDiff_eq (α β dt i : ℝ) : tickDiff α β dt i = exp (α - β * i) * Real.sqrt dt := rfl

theorem continuous_modelMu (β muF sigF Lhalf : ℝ) :
    Continuous (modelMu β muF sigF Lhalf) := by
  unfold modelMu
  fun_prop

theorem continuous_tickDrift (β dt muF sigF Lhalf : ℝ) :
    Continuous (tickDrift β dt muF sigF Lhalf) :=
  continuous_const.mul (continuous_modelMu β muF sigF Lhalf)

theorem continuous_tickDiff (α β dt : ℝ) : Continuous (tickDiff α β dt) := by
  unfold tickDiff TickDualMapping.vol
  fun_prop

/-! ### The tick bucket

The md restricts the state to a tick bucket `i ∈ [i_l, i_u]`.  Evaluating the coefficients at the
bucket-clamped state gives globally bounded coefficients (the standard local-boundedness
truncation) without touching the shape of the `σ` profile inside the bucket. -/

/-- Clamp a tick into the bucket `[il, iu]`. -/
noncomputable def bucket (il iu i : ℝ) : ℝ := max il (min iu i)

theorem continuous_bucket (il iu : ℝ) : Continuous (bucket il iu) := by
  unfold bucket; fun_prop

theorem bucket_mem {il iu : ℝ} (h : il ≤ iu) (i : ℝ) : il ≤ bucket il iu i ∧ bucket il iu i ≤ iu :=
  ⟨le_max_left _ _, max_le h (min_le_left _ _)⟩

theorem bucket_id {il iu i : ℝ} (h₁ : il ≤ i) (h₂ : i ≤ iu) : bucket il iu i = i := by
  unfold bucket
  rw [min_eq_right h₂, max_eq_right h₁]

/-- Bucket-truncated drift increment. -/
noncomputable def bucketDrift (β dt muF sigF Lhalf il iu : ℝ) (i : ℝ) : ℝ :=
  tickDrift β dt muF sigF Lhalf (bucket il iu i)

/-- Bucket-truncated diffusion increment. -/
noncomputable def bucketDiff (α β dt il iu : ℝ) (i : ℝ) : ℝ :=
  tickDiff α β dt (bucket il iu i)

theorem continuous_bucketDrift (β dt muF sigF Lhalf il iu : ℝ) :
    Continuous (bucketDrift β dt muF sigF Lhalf il iu) :=
  (continuous_tickDrift β dt muF sigF Lhalf).comp (continuous_bucket il iu)

theorem continuous_bucketDiff (α β dt il iu : ℝ) :
    Continuous (bucketDiff α β dt il iu) :=
  (continuous_tickDiff α β dt).comp (continuous_bucket il iu)

/-- Inside the bucket the truncated coefficients agree with the model ones, so the `σ (i)` profile
is unchanged on the bucket. -/
theorem bucketDiff_eq_tickDiff {il iu i : ℝ} (h₁ : il ≤ i) (h₂ : i ≤ iu) (α β dt : ℝ) :
    bucketDiff α β dt il iu i = tickDiff α β dt i := by
  rw [bucketDiff, bucket_id h₁ h₂]

theorem bucketDrift_eq_tickDrift {il iu i : ℝ} (h₁ : il ≤ i) (h₂ : i ≤ iu)
    (β dt muF sigF Lhalf : ℝ) :
    bucketDrift β dt muF sigF Lhalf il iu i = tickDrift β dt muF sigF Lhalf i := by
  rw [bucketDrift, bucket_id h₁ h₂]

/-- The truncated diffusion increment is globally bounded by its value at the lower tick. -/
theorem bucketDiff_abs_le {α β dt il iu : ℝ} (hβ : 0 < β) (hiu : il ≤ iu) (i : ℝ) :
    |bucketDiff α β dt il iu i| ≤ exp (α - β * il) * Real.sqrt dt := by
  obtain ⟨hlo, -⟩ := bucket_mem hiu i
  have hexp : exp (α - β * bucket il iu i) ≤ exp (α - β * il) := by
    apply Real.exp_le_exp.2
    have : β * il ≤ β * bucket il iu i := by nlinarith
    linarith
  have hpos : 0 < exp (α - β * bucket il iu i) := Real.exp_pos _
  have hsq : 0 ≤ Real.sqrt dt := Real.sqrt_nonneg dt
  rw [bucketDiff, tickDiff_eq, abs_of_nonneg (by positivity)]
  exact mul_le_mul_of_nonneg_right hexp hsq

/-- The truncated drift increment is bounded below by a positive constant, provided the drift is
positive on the bucket (i.e. the flow drift dominates the convexity correction at the lower tick).
-/
theorem bucketDrift_lower {β dt muF sigF Lhalf il iu : ℝ} (hβ : 0 < β) (hdt : 0 < dt)
    (hiu : il ≤ iu)
    (hdrift : sigF ^ 2 / (2 * Lhalf ^ 2) * exp (-(β * il)) < muF / Lhalf)
    (hsig : 0 ≤ sigF ^ 2 / (2 * Lhalf ^ 2)) (i : ℝ) :
    dt / β * (exp (-(β * iu)) * (muF / Lhalf - sigF ^ 2 / (2 * Lhalf ^ 2) * exp (-(β * il))))
      ≤ bucketDrift β dt muF sigF Lhalf il iu i := by
  obtain ⟨hlo, hhi⟩ := bucket_mem hiu i
  set y := bucket il iu i with hy
  set m₁ := muF / Lhalf with hm₁
  set m₂ := sigF ^ 2 / (2 * Lhalf ^ 2) with hm₂
  have hEle : exp (-(β * y)) ≤ exp (-(β * il)) := by
    apply Real.exp_le_exp.2; nlinarith
  have hEge : exp (-(β * iu)) ≤ exp (-(β * y)) := by
    apply Real.exp_le_exp.2; nlinarith
  have hEpos : 0 < exp (-(β * y)) := Real.exp_pos _
  have hfac : 0 < m₁ - m₂ * exp (-(β * il)) := by linarith
  have hkey : exp (-(β * iu)) * (m₁ - m₂ * exp (-(β * il)))
      ≤ exp (-(β * y)) * (m₁ - m₂ * exp (-(β * y))) := by
    have h1 : m₁ - m₂ * exp (-(β * il)) ≤ m₁ - m₂ * exp (-(β * y)) := by
      nlinarith
    calc exp (-(β * iu)) * (m₁ - m₂ * exp (-(β * il)))
        ≤ exp (-(β * y)) * (m₁ - m₂ * exp (-(β * il))) := by nlinarith
      _ ≤ exp (-(β * y)) * (m₁ - m₂ * exp (-(β * y))) := by nlinarith
  have hmu : modelMu β muF sigF Lhalf y = exp (-(β * y)) * (m₁ - m₂ * exp (-(β * y))) := by
    unfold modelMu; ring
  rw [bucketDrift, tickDrift, ← hy, hmu]
  have hdtβ : 0 < dt / β := div_pos hdt hβ
  exact mul_le_mul_of_nonneg_left hkey (le_of_lt hdtβ)

/-! ### Existence of `κ⋆` for the model -/

/-- **Existence of the pinning drift scale for the md model.**
For an arbitrary fixed exogenous shock stream `ε`, a starting tick `i0`, a horizon `N ≥ 1`, a tick
bucket `[il, iu]` on which the drift is positive, there is a drift scale `κ⋆` — bracketed
explicitly — whose diffusion-shaped path lands exactly on the terminal tick `iT`.  Taking
`iT = (α - ln σ̄) / β` this is the tick implied by the target volatility `σ̄`. -/
theorem exists_kappa_model {α β dt muF sigF Lhalf il iu : ℝ} (ε : ℕ → ℝ) (i0 iT : ℝ) {N : ℕ}
    (hβ : 0 < β) (hdt : 0 < dt) (hiu : il ≤ iu) (hN : 0 < N)
    (hdrift : sigF ^ 2 / (2 * Lhalf ^ 2) * exp (-(β * il)) < muF / Lhalf)
    (hsig : 0 ≤ sigF ^ 2 / (2 * Lhalf ^ 2)) :
    ∃ κ : ℝ, tickRec (bucketDrift β dt muF sigF Lhalf il iu) (bucketDiff α β dt il iu)
      ε i0 κ N = iT := by
  set d₀ := dt / β *
    (exp (-(β * iu)) * (muF / Lhalf - sigF ^ 2 / (2 * Lhalf ^ 2) * exp (-(β * il)))) with hd₀def
  have hd₀ : 0 < d₀ := by
    have h1 : 0 < dt / β := div_pos hdt hβ
    have h2 : 0 < exp (-(β * iu)) := Real.exp_pos _
    have h3 : 0 < muF / Lhalf - sigF ^ 2 / (2 * Lhalf ^ 2) * exp (-(β * il)) := by linarith
    rw [hd₀def]; positivity
  obtain ⟨κ, -, hκ⟩ :=
    exists_kappa_of_bounds (D := bucketDrift β dt muF sigF Lhalf il iu)
      (S := bucketDiff α β dt il iu) (d₀ := d₀) (Sm := exp (α - β * il) * Real.sqrt dt)
      ε i0 iT (continuous_bucketDrift _ _ _ _ _ _ _) (continuous_bucketDiff _ _ _ _ _) hd₀
      (fun x => bucketDrift_lower hβ hdt hiu hdrift hsig x)
      (fun x => bucketDiff_abs_le hβ hiu x) hN
  exact ⟨κ, hκ⟩

/-! ## Part 3: the forge schedule

Terminal tick implied by the target volatility, the pinning drift scale `κ⋆`, the emitted path,
and the statement that it realizes `σ̄`. -/

/-- The terminal tick implied by the target volatility: `i (N) = (α - ln σ̄) / β`. -/
noncomputable def terminalTick (α β sigbar : ℝ) : ℝ := (α - Real.log sigbar) / β

theorem vol_terminalTick {α β sigbar : ℝ} (hβ : β ≠ 0) (hσ : 0 < sigbar) :
    TickDualMapping.vol α β (terminalTick α β sigbar) = sigbar :=
  (TickDualMapping.terminal_tick_unique α β sigbar hβ hσ _).2 rfl

/-- Hypotheses of the forge cron: model parameters, bucket, horizon and target. -/
structure ForgeParams where
  /-- `α = ln (σ_F / (L ln 1.0001))`, the intercept of `ln σ`. -/
  alpha : ℝ
  /-- `β = ln 1.0001`, the slope of `ln σ` in the tick. -/
  beta : ℝ
  /-- The fixed time step `d̄t`. -/
  dt : ℝ
  /-- Net-flow drift `μ_F`. -/
  muF : ℝ
  /-- Net-flow volatility `σ_F`. -/
  sigF : ℝ
  /-- Half-liquidity `L_{1/2}`. -/
  Lhalf : ℝ
  /-- Lower tick of the bucket. -/
  il : ℝ
  /-- Upper tick of the bucket. -/
  iu : ℝ
  /-- Starting tick `i (0)`. -/
  i0 : ℝ
  /-- Target realized volatility `σ̄`. -/
  sigbar : ℝ
  /-- Number of steps `N = Window / d̄t`. -/
  N : ℕ
  beta_pos : 0 < beta
  dt_pos : 0 < dt
  bucket_le : il ≤ iu
  N_pos : 0 < N
  sigbar_pos : 0 < sigbar
  /-- The flow drift dominates the convexity correction at the lower tick, so the drift increment
  is positive on the whole bucket. -/
  drift_pos : sigF ^ 2 / (2 * Lhalf ^ 2) * exp (-(beta * il)) < muF / Lhalf
  sig_nonneg : 0 ≤ sigF ^ 2 / (2 * Lhalf ^ 2)

namespace ForgeParams

variable (P : ForgeParams)

/-- Drift increment of the schedule (bucket-truncated md drift). -/
noncomputable def D : ℝ → ℝ := bucketDrift P.beta P.dt P.muF P.sigF P.Lhalf P.il P.iu

/-- Diffusion increment of the schedule (bucket-truncated md `σ (i) √d̄t`). -/
noncomputable def S : ℝ → ℝ := bucketDiff P.alpha P.beta P.dt P.il P.iu

/-- The terminal tick pinned by the target volatility. -/
noncomputable def iN : ℝ := terminalTick P.alpha P.beta P.sigbar

/-- The tick path generated by drift scale `κ` and shock stream `ε`. -/
noncomputable def path (ε : ℕ → ℝ) (κ : ℝ) : ℕ → ℝ := tickRec P.D P.S ε P.i0 κ

theorem path_zero (ε : ℕ → ℝ) (κ : ℝ) : P.path ε κ 0 = P.i0 := rfl

theorem path_succ (ε : ℕ → ℝ) (κ : ℝ) (j : ℕ) :
    P.path ε κ (j + 1) = P.path ε κ j + κ * P.D (P.path ε κ j) + P.S (P.path ε κ j) * ε (j + 1) :=
  tickRec_succ _ _ _ _ _ _

/-- Existence of a pinning drift scale for this parameter set and any fixed shock stream. -/
theorem exists_kappa (ε : ℕ → ℝ) : ∃ κ : ℝ, P.path ε κ P.N = P.iN :=
  exists_kappa_model ε P.i0 P.iN P.beta_pos P.dt_pos P.bucket_le P.N_pos P.drift_pos P.sig_nonneg

/-- **`κ⋆`** — the drift scale that pins the terminal tick, for the given shock stream. -/
noncomputable def kappaStar (ε : ℕ → ℝ) : ℝ := (P.exists_kappa ε).choose

theorem kappaStar_spec (ε : ℕ → ℝ) : P.path ε (P.kappaStar ε) P.N = P.iN :=
  (P.exists_kappa ε).choose_spec

/-- **The emitted `TickHistory`**: the path run with the pinning drift scale. -/
noncomputable def forgePath (ε : ℕ → ℝ) : ℕ → ℝ := P.path ε (P.kappaStar ε)

theorem forgePath_zero (ε : ℕ → ℝ) : P.forgePath ε 0 = P.i0 := rfl

theorem forgePath_succ (ε : ℕ → ℝ) (j : ℕ) :
    P.forgePath ε (j + 1)
      = P.forgePath ε j + P.kappaStar ε * P.D (P.forgePath ε j)
        + P.S (P.forgePath ε j) * ε (j + 1) :=
  P.path_succ ε _ j

/-- The emitted path reaches the terminal tick implied by `σ̄`. -/
theorem forgePath_terminal (ε : ℕ → ℝ) : P.forgePath ε P.N = P.iN := P.kappaStar_spec ε

/-- **The emitted path realizes the target volatility**: `σ (i N) = σ̄`. -/
theorem forgePath_vol_terminal (ε : ℕ → ℝ) :
    TickDualMapping.vol P.alpha P.beta (P.forgePath ε P.N) = P.sigbar := by
  rw [P.forgePath_terminal ε, iN]
  exact vol_terminalTick (ne_of_gt P.beta_pos) P.sigbar_pos

/-- The `σ (i)` profile along the emitted path is the model one, `σ (i) = exp (α - β i)`; the
drift scale `κ⋆` does not deform it. -/
theorem forgePath_vol (ε : ℕ → ℝ) (j : ℕ) :
    TickDualMapping.vol P.alpha P.beta (P.forgePath ε j) = exp (P.alpha - P.beta * P.forgePath ε j) :=
  rfl

/-- The shock at step `j + 1` enters with coefficient `σ (i j) √d̄t` whenever the lagged tick lies
in the bucket: the diffusion coefficient of the md SDE is preserved exactly. -/
theorem forgePath_diffusion_coeff (ε : ℕ → ℝ) (j : ℕ)
    (h₁ : P.il ≤ P.forgePath ε j) (h₂ : P.forgePath ε j ≤ P.iu) :
    P.forgePath ε (j + 1) - P.forgePath ε j - P.kappaStar ε * P.D (P.forgePath ε j)
      = TickDualMapping.vol P.alpha P.beta (P.forgePath ε j) * Real.sqrt P.dt * ε (j + 1) := by
  rw [P.forgePath_succ ε j]
  have : P.S (P.forgePath ε j) = TickDualMapping.vol P.alpha P.beta (P.forgePath ε j)
      * Real.sqrt P.dt := by
    rw [S, bucketDiff_eq_tickDiff h₁ h₂, tickDiff]
  rw [this]; ring

/-- Uniqueness of `κ⋆` under the step-size condition: if each Euler step is nondecreasing in the
state, no other drift scale reaches the terminal tick. -/
theorem kappaStar_unique (ε : ℕ → ℝ)
    (hstep : ∀ (κ : ℝ) (j : ℕ), Monotone fun x : ℝ => x + κ * P.D x + P.S x * ε j)
    {κ : ℝ} (hκ : P.path ε κ P.N = P.iN) : κ = P.kappaStar ε := by
  have hpos : ∀ x, 0 < P.D x := by
    intro x
    have h := bucketDrift_lower (β := P.beta) (dt := P.dt) (muF := P.muF) (sigF := P.sigF)
      (Lhalf := P.Lhalf) (il := P.il) (iu := P.iu) P.beta_pos P.dt_pos P.bucket_le P.drift_pos
      P.sig_nonneg x
    have h1 : 0 < P.dt / P.beta := div_pos P.dt_pos P.beta_pos
    have h2 : (0 : ℝ) < exp (-(P.beta * P.iu)) := Real.exp_pos _
    have h3 : 0 < P.muF / P.Lhalf
        - P.sigF ^ 2 / (2 * P.Lhalf ^ 2) * exp (-(P.beta * P.il)) := by
      have := P.drift_pos; linarith
    have h4 : 0 < P.dt / P.beta * (exp (-(P.beta * P.iu)) *
        (P.muF / P.Lhalf - P.sigF ^ 2 / (2 * P.Lhalf ^ 2) * exp (-(P.beta * P.il)))) := by
      positivity
    exact lt_of_lt_of_le h4 h
  exact kappa_unique ε P.i0 P.iN hpos hstep P.N_pos hκ (P.kappaStar_spec ε)

end ForgeParams

/-- A witness that the hypotheses of `ForgeParams` are jointly satisfiable (so none of the
statements above is vacuous): unit slope and step, unit half-liquidity and flow drift, no flow
volatility, bucket `[0, 1]`, one step, unit target volatility. -/
noncomputable def exampleParams : ForgeParams where
  alpha := 1; beta := 1; dt := 1; muF := 1; sigF := 0; Lhalf := 1
  il := 0; iu := 1; i0 := 0; sigbar := 1; N := 1
  beta_pos := one_pos
  dt_pos := one_pos
  bucket_le := zero_le_one
  N_pos := Nat.one_pos
  sigbar_pos := one_pos
  drift_pos := by norm_num
  sig_nonneg := by norm_num

/-! ## Forge evaluation order

A machine-checkable transcript of the consumer's evaluation order: from a fixed shock stream
`ε` (step 1: reveal seed ⊕ blockhash → PRNG), solve for `κ⋆` (step 2), and emit the path
(step 3).  The three components below are exactly what the forge script writes out. -/

/-- The output of the cron: the pinning drift scale and the tick history it generates. -/
noncomputable def forgeEvaluationOrder (P : ForgeParams) (ε : ℕ → ℝ) : ℝ × (ℕ → ℝ) :=
  -- 1. `ε` is given (exogenous);  2. solve `κ⋆`;  3. emit `{i j}`.
  (P.kappaStar ε, P.forgePath ε)

/-- The emitted tick history starts at `i (0)`, follows the diffusion-shaped recursion driven by
the given shocks, and terminates at the tick whose volatility is exactly the target `σ̄`. -/
theorem forgeEvaluationOrder_spec (P : ForgeParams) (ε : ℕ → ℝ) :
    let out := forgeEvaluationOrder P ε
    out.2 0 = P.i0 ∧
    (∀ j, out.2 (j + 1) = out.2 j + out.1 * P.D (out.2 j) + P.S (out.2 j) * ε (j + 1)) ∧
    TickDualMapping.vol P.alpha P.beta (out.2 P.N) = P.sigbar :=
  ⟨rfl, fun j => P.forgePath_succ ε j, P.forgePath_vol_terminal ε⟩

end TickControlLayer
