{-# LANGUAGE OverloadedStrings #-}

-- |
-- The demo driver. One @cabal run@ exercises BOTH price mechanisms and the order generator against
-- the live rig, and leaves a committed, replayable record of the DRIV-01 run behind.
--
-- == THE ORDER OF THE THREE THINGS THAT HAPPEN BEFORE ANY RPC
--
--   1. @load_rig@ — every address and every topic0 below comes from the manifest and the pin file.
--      A missing, stale or malformed manifest stops the program HERE rather than after a
--      transaction has gone to an address that used to be right.
--   2. @resolve_seed@ — and the seed is PRINTED immediately, before the run, so a crashed run still
--      tells the operator how to replay it. Until 22-05 this line was mwc-random's system-entropy
--      constructor: unseeded, unrecorded, and therefore unreplayable. That name is deliberately not
--      written out here, because the acceptance criterion for this file is a grep that must find
--      zero occurrences of it — a historical note that quoted it would defeat the check whose whole
--      job is to notice the call coming back.
--   3. the capture 'IORef's — created before the Web3 action so the exception handler can reach
--      them.
--
-- == THE TWO PRICE MECHANISMS, BOTH KEPT
--
-- @write_price@ + @run_price_gen@ drive @PriceSetterHook@'s own pool on the SECOND, liquidity-free
-- @PoolManager@. They write slot0 and emit nothing, which is precisely why they could never have
-- satisfied DRIV-01 on their own — and roadmap SC-1 requires them to stay available and unchanged,
-- so @run_cheat_swap_path@ was added BESIDE them, not in place of them.
--
-- == FLUSH ON FAILURE
--
-- A @fail@ inside 'Network.Web3.Provider.Web3' surfaces as an UNCAUGHT 'IOException', not as
-- @runWeb3'@'s 'Left', and it can fire MID-FOLD after earlier steps have already mined.
-- 22-CONTEXT's G2 is why this driver aborts on the first bad step instead of completing: once a bad
-- timestamp lands, the oracle's window math is silently wrong for everything after it, so a
-- complete-and-report-all run would produce evidence that LOOKS fine and is not. Aborting is only
-- useful if the partial run survives, so the whole @runWeb3'@ is wrapped in 'finally' over the
-- steps 'IORef'.
--
-- The handler must never throw: a failed flush that masked the original error would turn a
-- diagnosable failure into a mystery. It catches everything and prints the path.
module Main where

import Control.Exception (SomeException, displayException, finally, try)
import Control.Monad.IO.Class (liftIO)
import Data.Bits (shiftR, (.&.))
import qualified Data.ByteString as BS
import Data.Char (intToDigit, isSpace)
import Data.IORef (IORef, newIORef, readIORef, writeIORef)
import Data.List (dropWhileEnd)
import qualified Data.Text as T
import Data.Word (Word32)
import System.Process (readProcess)

import Sample
  ( sample_order
  , sample_order_gen
  , sample_price_gen
  , sample_stride
  , sample_tick
  )
import Data.ByteArray.HexString (HexString, toBytes)
import Data.Solidity.Prim.Address (Address, toHexString)
import Network.Ethereum.Api.Types (unQuantity)
import Network.Web3.Provider (Provider (HttpProvider), runWeb3')

import CheatSwap.Rpc (CheatSwapStep (..), CheatSwapTarget (..))
import Driver.Capture
  ( DriverRig (..)
  , DriverRun (..)
  , DriverSeed (..)
  , E3Record (..)
  , E5Record (..)
  , LegacyWritePrice (..)
  , StepRecord
  , capture_path
  , step_record
  , write_capture
  )
import Driver.Seed (gen_from_seed, resolve_seed, seed_env_var)
import PriceSetter.Report (report_price_write)
import PriceSetter.Rpc (write_price)
import RealizedVol.Decode (FeeApplied (..), TimepointWritten (..))
import Rig.Manifest
  ( Rig (..)
  , RigAccounts (..)
  , RigAddresses (..)
  , RigPool (..)
  , contract_address
  , load_rig
  , pin_topic0
  , resolve_account
  , resolve_contract
  )
import StochasticOrderGen.Report (report_batch_result)
import StochasticOrderGen.Rpc (run_order_gen)
import StochasticPriceGen.Report (report_path_write)
import StochasticPriceGen.Rpc (run_cheat_swap_path, run_price_gen)
import StochasticPriceGen.Types (StochasticPriceGen (size))
import VolOrder.Report (report_receipt)
import VolOrder.Rpc (create_order)

main :: IO ()
main = do
  -- The rig is loaded FIRST -- before the RNG, before the provider, before any RPC call.
  --
  -- Every address this driver touches and the topic0s it decodes with are read here, from
  -- offchain/rig/rig-manifest.json (written by offchain/rig/deploy-rig.sh) and
  -- offchain/rig/rig-pins.json (generated by offchain/rig/generate-pins.sh). There is no
  -- literal, no default and no fallback anywhere below: a missing, stale or malformed manifest
  -- stops the program HERE, naming the resolved path and the command that produces it, rather
  -- than sending a transaction to an address that used to be right.
  rig <- load_rig
  let addrs = rig_addrs rig
      pool  = rig_pool addrs

  sender   <- either fail pure (resolve_account  rig "sender")
  deployer <- either fail pure (resolve_account  rig "deployer")
  manager  <- either fail pure (resolve_contract rig "VolOrderManagerMod")
  psh      <- either fail pure (resolve_contract rig "PriceSetterHook")
  pm       <- either fail pure (resolve_contract rig "PoolManager")
  fee_hook <- either fail pure (resolve_contract rig "DynamicFeeHook")
  router   <- either fail pure (resolve_contract rig "PoolSwapTest")
  topic_e1 <- either fail pure (pin_topic0       rig "VolOrderCreated")
  topic_e3 <- either fail pure (pin_topic0       rig "TimepointWritten")
  topic_e5 <- either fail pure (pin_topic0       rig "FeeApplied")

  -- The seed is resolved and PRINTED before anything is sent. A run that dies at step 3 still
  -- leaves the operator a line they can paste straight back in to reproduce it exactly.
  (seed, seed_note) <- resolve_seed
  putStrLn (seed_env_var ++ "=" ++ show seed)
  putStrLn ("  " ++ seed_note)
  gen <- gen_from_seed seed

  -- The cheat manager and the read manager are the SAME address, always. CheatSwapTarget splits
  -- them only so 22-04 could aim a measurement at the wrong one and observe the silence.
  let target = CheatSwapTarget
        { cst_cheat_manager = pm
        , cst_pool_manager  = pm
        , cst_price_hook    = psh
        , cst_fee_hook      = fee_hook
        , cst_swap_router   = router
        , cst_deployer      = deployer
        , cst_pool_id       = read (T.unpack (rig_pool_id pool))
        , cst_currency0     = T.unpack (rig_currency0 pool)
        , cst_currency1     = T.unpack (rig_currency1 pool)
        , cst_tick_spacing  = rig_tick_spacing pool
        , cst_topic_e3      = topic_e3
        , cst_topic_e5      = topic_e5
        }

  steps_ref  <- newIORef []
  legacy_ref <- newIORef Nothing
  done_ref   <- newIORef False

  capture <- capture_path

  result <-
    flip finally (flush rig seed steps_ref legacy_ref done_ref capture) $
      runWeb3'
        (HttpProvider "http://127.0.0.1:8545")
        (do receipt <- create_order sender manager sample_order

            -- The LEGACY flow, unchanged and still first-class (roadmap SC-1).
            written <- write_price psh sample_tick
            liftIO (writeIORef legacy_ref (Just (legacy_record sample_tick written)))
            path_written <- run_price_gen psh sample_price_gen gen

            -- DRIV-01: the stochastic price path, one E3 per step.
            steps <- run_cheat_swap_path target sample_price_gen sample_stride steps_ref gen

            -- The DRIV-01 path is complete HERE. Anything that fails after this point is an
            -- order-side failure and must not mark the price-path evidence partial.
            liftIO (writeIORef done_ref True)

            batch_results <- run_order_gen sender manager sample_order_gen gen
            pure (receipt, written, path_written, steps, batch_results))

  case result of
    Left web3_error -> putStrLn ("rpc error: " ++ show web3_error)
    Right (receipt, written, path_written, steps, batch_results) -> do
      report_receipt topic_e1 receipt
      report_price_write written
      report_path_write path_written
      mapM_ (putStrLn . summarise_step) (zip [0 :: Int ..] steps)
      putStrLn ("wrote " ++ capture ++ "  (" ++ show (length steps) ++ " steps)")
      mapM_ report_batch_result batch_results

-- ---------------------------------------------------------------------------------------------
-- The flush
-- ---------------------------------------------------------------------------------------------

-- | Build and write the run record from whatever the fold managed to record.
--
-- Runs on BOTH paths. On the happy path @done_ref@ is 'True' and the artifact is complete; on the
-- exception path it is 'False', @dr_steps@ is short of @dr_configured_size@, and @dr_complete@ says
-- so — which is what lets an offline check refuse to treat a partial run as evidence.
--
-- @t0@ is the FIRST recorded step's own submitted timestamp, which is @chain_head + stride@ by
-- construction. It is 'Nothing' when nothing mined, because a run with no origin has none to record
-- and inventing one would make the artifact lie.
flush
  :: Rig
  -> Word32
  -> IORef [CheatSwapStep]
  -> IORef (Maybe LegacyWritePrice)
  -> IORef Bool
  -> FilePath
  -> IO ()
flush rig seed steps_ref legacy_ref done_ref path = do
  outcome <- try $ do
    steps  <- readIORef steps_ref
    legacy <- readIORef legacy_ref
    done   <- readIORef done_ref
    stamp  <- iso_timestamp

    let addrs = rig_addrs rig
        pool  = rig_pool addrs
        run = DriverRun
          { dr_generated_at    = stamp
          , dr_chain_id        = rig_chain_id addrs
          , dr_generated_from  = T.unpack (rig_generated_from addrs)
          , dr_complete        = done
          , dr_configured_size = size sample_price_gen
          , dr_rig = DriverRig
              { drg_pool_manager      = manifest_contract rig "PoolManager"
              , drg_dynamic_fee_hook  = manifest_contract rig "DynamicFeeHook"
              , drg_price_setter_hook = manifest_contract rig "PriceSetterHook"
              , drg_swap_router       = manifest_contract rig "PoolSwapTest"
              , drg_vol_order_manager = manifest_contract rig "VolOrderManagerMod"
              , drg_pool_id           = T.unpack (rig_pool_id pool)
              , drg_tick_spacing      = rig_tick_spacing pool
              , drg_deployer          = T.unpack (rig_deployer (rig_accounts addrs))
              , drg_sender            = T.unpack (rig_sender   (rig_accounts addrs))
              }
          , dr_seed = DriverSeed
              { ds_rng    = seed
              , ds_t0     = case steps of
                              (first_step : _) -> Just (cs_timestamp first_step)
                              []               -> Nothing
              , ds_stride = sample_stride
              }
          , dr_steps              = zipWith to_step [0 ..] steps
          , dr_legacy_write_price = legacy
          }
    write_capture path run

  case outcome :: Either SomeException () of
    Right () -> pure ()
    Left err ->
      -- Deliberately swallowed. If the flush itself fails, the ORIGINAL error is the one worth
      -- propagating; re-raising here would replace a diagnosable failure with a mystery.
      putStrLn ("WARNING: could not write the driver capture to " ++ path ++ ": "
                 ++ displayException err)

to_step :: Int -> CheatSwapStep -> StepRecord
to_step k step =
  step_record
    k
    (cs_tick step)
    (cs_timestamp step)
    (Just (hex_of (cs_tx_hash step)))
    (fmap unQuantity (cs_status step))
    (Just (cs_e3_count step))
    (Just (cs_e5_count step))
    (fmap e3_record (cs_e3 step))
    (fmap e5_record (cs_e5 step))

e3_record :: TimepointWritten -> E3Record
e3_record e =
  E3Record
    { e3r_timestamp = tw_timestamp e
    , e3r_tick      = tw_tick e
    , e3r_vol_cum   = tw_vol_cum e
    , e3r_avg_tick  = tw_avg_tick e
    , e3r_tick_cum  = tw_tick_cum e
    }

e5_record :: FeeApplied -> E5Record
e5_record e = E5Record { e5r_sigma = fa_sigma e, e5r_fee = fa_fee e }

-- | What @write_price@ returned, as the artifact records it. Its @poolManager@ is the OTHER
-- manager, and pinning that is the point: it is why this flow is ADDED BESIDE the driver rather
-- than being the driver.
legacy_record :: Integer -> (Address, HexString, HexString) -> LegacyWritePrice
legacy_record tick (pool_manager, slot, value) =
  LegacyWritePrice
    { lwp_tick         = tick
    , lwp_pool_manager = address_hex pool_manager
    , lwp_slot         = hex_of slot
    , lwp_value        = hex_of value
    }

address_hex :: Address -> String
address_hex = hex_of . toHexString

-- ---------------------------------------------------------------------------------------------
-- Reporting and small helpers
-- ---------------------------------------------------------------------------------------------

summarise_step :: (Int, CheatSwapStep) -> String
summarise_step (k, step) =
  "  step " ++ show k
    ++ "  tick=" ++ show (cs_tick step)
    ++ "  ts=" ++ show (cs_timestamp step)
    ++ "  status=" ++ show (fmap unQuantity (cs_status step))
    ++ "  e3=" ++ show (cs_e3_count step)
    ++ "  e5=" ++ show (cs_e5_count step)
    ++ "  e3.tick=" ++ maybe "-" (show . tw_tick) (cs_e3 step)

manifest_contract :: Rig -> T.Text -> String
manifest_contract rig name =
  either (error . (("driver capture: " ++ T.unpack name ++ " -- ") ++)) T.unpack
         (contract_address rig name)

-- | @0x@-prefixed lowercase hex, rendered from the bytes so the shape is this program's decision
-- and so nothing here is a source literal the offchain purge could match.
hex_of :: HexString -> String
hex_of = ("0x" ++) . concatMap byte . BS.unpack . toBytes
  where
    byte b = [nibble (b `shiftR` 4), nibble (b .&. 0x0f)]
    nibble = intToDigit . fromIntegral

-- | The capture timestamp, from @date@ rather than a new @time@ dependency -- the same move
-- @capture-batch-return.sh@ and @CheatSwapProof.hs@ both make.
iso_timestamp :: IO String
iso_timestamp = trim <$> readProcess "date" ["-u", "+%Y-%m-%dT%H:%M:%SZ"] ""

trim :: String -> String
trim = dropWhileEnd isSpace . dropWhile isSpace
