{-# LANGUAGE OverloadedStrings #-}

module Main where

import System.Random.MWC (createSystemRandom)

import Sample
  ( sample_order
  , sample_order_gen
  , sample_price_gen
  , sample_tick
  )
import Network.Web3.Provider (Provider (HttpProvider), runWeb3')
import PriceSetter.Report (report_price_write)
import PriceSetter.Rpc (write_price)
import Rig.Manifest (load_rig, pin_topic0, resolve_account, resolve_contract)
import StochasticOrderGen.Report (report_batch_result)
import StochasticOrderGen.Rpc (run_order_gen)
import StochasticPriceGen.Report (report_path_write)
import StochasticPriceGen.Rpc (run_price_gen)
import VolOrder.Report (report_receipt)
import VolOrder.Rpc (create_order)

main :: IO ()
main = do
  -- The rig is loaded FIRST -- before the RNG, before the provider, before any RPC call.
  --
  -- Every address this driver touches and the E1 topic0 it decodes with are read here, from
  -- offchain/rig/rig-manifest.json (written by offchain/rig/deploy-rig.sh) and
  -- offchain/rig/rig-pins.json (generated by offchain/rig/generate-pins.sh). There is no
  -- literal, no default and no fallback anywhere below: a missing, stale or malformed manifest
  -- stops the program HERE, naming the resolved path and the command that produces it, rather
  -- than sending a transaction to an address that used to be right.
  rig <- load_rig
  sender   <- either fail pure (resolve_account  rig "sender")
  manager  <- either fail pure (resolve_contract rig "VolOrderManagerMod")
  psh      <- either fail pure (resolve_contract rig "PriceSetterHook")
  topic_e1 <- either fail pure (pin_topic0       rig "VolOrderCreated")

  -- Created before entering the Web3 action (main is already IO, so no
  -- liftIO is needed here) -- run_price_gen/run_order_gen below just take
  -- the resulting GenIO value, consuming its random stream sequentially.
  gen <- createSystemRandom

  result <-
    runWeb3'
      (HttpProvider "http://127.0.0.1:8545")
      (do receipt <- create_order sender manager sample_order
          written <- write_price psh sample_tick
          path_written <- run_price_gen psh sample_price_gen gen
          batch_results <- run_order_gen sender manager sample_order_gen gen
          pure (receipt, written, path_written, batch_results))

  case result of
    Left web3_error -> putStrLn ("rpc error: " ++ show web3_error)
    Right (receipt, written, path_written, batch_results) -> do
      report_receipt topic_e1 receipt
      report_price_write written
      report_path_write path_written
      mapM_ report_batch_result batch_results
