-- 003_version_columns_nonempty.sql -- the empty toolchain version, made unstorable.
--
-- THE MEASUREMENT THIS ANSWERS. 001_model_run.sql declares gams_ver and conopt_ver as
-- `text not null`, and NOT NULL DOES NOT FORBID THE EMPTY STRING. MEASURED at 24-RESEARCH M14 and
-- re-observed against a real server by the capture that accompanies this migration: before this
-- file existed the schema stored '' in both columns without a word of complaint. Phase 24 built a
-- GamsVersion whose constructor is not exported and which therefore has no empty inhabitant, and
-- that is the primary defence -- but it is a Haskell defence, and this table is written to by a
-- process, not by a type. This constraint is the layer that outlives every Haskell refactor and
-- every future writer that is not Store.Postgres.
--
-- WHY AN EMPTY VERSION IS THE WORST VALUE THIS TABLE CAN HOLD. KEY-01 folds both version strings
-- into the content key. If detection succeeds emptily, every toolchain hashes to the same key
-- component, so GAMS 54.1's bytes are served to a GAMS 55 request -- the precise scenario
-- VOLUME_PATH.md section 3 warns about: "a different CONOPT version may select a different member
-- of the underdetermined path family -- still passing every gate". The output is well-formed, every
-- named abort is quiet, and the answer belongs to a solver nobody asked for.
--
-- AND AFTERWARDS THE POISONED ROWS ARE INDISTINGUISHABLE FROM THE GOOD ONES. The only evidence of
-- which toolchain produced a row is the column that was emptied. There is no second witness to
-- recover it from: raw is the artifact, doc is derived from raw in the same statement, and neither
-- carries a toolchain identity. A repair pass would have nothing to sort the rows by. That is why
-- this lands BEFORE the store's first production write rather than after the first bad row.
--
-- LENGTH, NOT <>. `length(col) > 0` is false for the empty string and NULL for a NULL, and a CHECK
-- passes on NULL -- which is correct here and deliberately relied upon: the NOT NULL declared in
-- 001 is the constraint that answers NULL, and this one answers ''. Two conjuncts, one per column,
-- because a constraint that covered only gams_ver is exactly the shape a copy-paste produces and
-- the capture attempts BOTH columns independently for that reason.
--
-- The constraint is NAMED, in the style of model_run_identity, because Store.Schema states the name
-- as data and the capture asserts that the server's own error message carries it. An unnamed check
-- would report a system-generated identifier and the recorded evidence could not say WHICH
-- constraint refused.
alter table model_run
  add constraint model_run_versions_nonempty
  check (length(gams_ver) > 0 and length(conopt_ver) > 0);
