{-# LANGUAGE OverloadedStrings #-}

-- |
-- One loud-failing loader for the rig's split manifest.
--
-- The rig's description of itself lives in two files, and a caller should not have to know
-- that:
--
--   * @offchain\/rig\/rig-pins.json@ -- COMMITTED, generated by @offchain\/rig\/generate-pins.sh@
--     from the imported interface files. Static: selectors, topic0s, and a @retired@ block.
--   * @offchain\/rig\/rig-manifest.json@ -- GITIGNORED, written by @offchain\/rig\/deploy-rig.sh@
--     on every deploy. Per-deploy: chain id, accounts, contract addresses, pool, seed.
--
-- 'load_rig' returns ONE 'Rig' carrying both halves.
--
-- EVERY field is mandatory. There is no optional-field fallback and no defaulted address
-- anywhere in this module, by design: a rig whose manifest is missing @PoolManager@ is not a
-- rig with an empty @PoolManager@, it is a broken rig, and the drivers must find that out at
-- startup rather than by sending a transaction to the zero address. A missing file or a
-- missing field is an immediate, loud, actionable failure.
module Rig.Manifest
  ( -- * Static pins
    PinEntry (..)
  , RigPins (..)
    -- * Per-deploy addresses
  , RigAccounts (..)
  , RigPool (..)
  , RigSeed (..)
  , RigAddresses (..)
    -- * Both halves
  , Rig (..)
    -- * Path resolution
  , rig_pins_path
  , rig_manifest_path
    -- * Loading
  , load_rig
  , load_rig_from
  , required_contracts
    -- * Lookups
  , contract_address
  , pin_selector
  , pin_topic0
  ) where

import Control.Exception (IOException, try)
import Data.Aeson (FromJSON (..), Value, eitherDecodeFileStrict, withObject, (.:))
import Data.Aeson.Key (Key)
import Data.Aeson.Types (Parser)
import Data.List (intercalate, sort)
import Data.Map.Strict (Map)
import qualified Data.Map.Strict as Map
import Data.Maybe (fromMaybe)
import Data.Text (Text)
import qualified Data.Text as T
import Numeric (readHex)
import System.Environment (lookupEnv)

-- ---------------------------------------------------------------------------------------------
-- Types
-- ---------------------------------------------------------------------------------------------

-- | One generated pin. 'pin_signature' is the exact string the value was computed from and
-- 'pin_source' the interface file it was parsed out of, so a reader can re-derive the value
-- without this module.
data PinEntry = PinEntry
  { pin_signature :: Text
  , pin_value     :: Text
  , pin_source    :: Text
  }
  deriving (Eq, Show)

-- | The contents of @rig-pins.json@.
data RigPins = RigPins
  { pin_selectors       :: Map Text PinEntry
  , pin_topics          :: Map Text PinEntry
  , pin_retired         :: Map Text Text
  , pins_generated_from :: Text
  }
  deriving (Eq, Show)

data RigAccounts = RigAccounts
  { rig_deployer :: Text
  , rig_sender   :: Text
  }
  deriving (Eq, Show)

data RigPool = RigPool
  { rig_pool_id      :: Text
  , rig_currency0    :: Text
  , rig_currency1    :: Text
  , rig_tick_spacing :: Integer
  }
  deriving (Eq, Show)

data RigSeed = RigSeed
  { rig_init_ts   :: Integer
  , rig_init_tick :: Integer
  }
  deriving (Eq, Show)

-- | The contents of @rig-manifest.json@.
data RigAddresses = RigAddresses
  { rig_chain_id       :: Integer
  , rig_generated_at   :: Text
  , rig_generated_from :: Text
  , rig_accounts       :: RigAccounts
  , rig_contracts      :: Map Text Text
  , rig_pool           :: RigPool
  , rig_seed           :: RigSeed
  }
  deriving (Eq, Show)

-- | Both halves of the split manifest.
data Rig = Rig
  { rig_pins  :: RigPins
  , rig_addrs :: RigAddresses
  }
  deriving (Eq, Show)

-- ---------------------------------------------------------------------------------------------
-- Decoding -- the mandatory field operator for every field. No optional-field operator and no
-- defaulted fallback appears anywhere below, so a key that is absent is a decode ERROR.
-- ---------------------------------------------------------------------------------------------

-- | Selector entries carry their value under @selector@ and topic entries under @topic0@, so
-- the value key is a parameter rather than a fallback between two alternatives.
pin_entry_with :: Key -> Value -> Parser PinEntry
pin_entry_with value_key = withObject "pin entry" $ \o ->
  PinEntry
    <$> o .: "signature"
    <*> o .: value_key
    <*> o .: "source"

instance FromJSON RigPins where
  parseJSON = withObject "rig-pins.json" $ \o -> do
    selectors <- o .: "selectors" >>= traverse (pin_entry_with "selector")
    topics    <- o .: "topics"    >>= traverse (pin_entry_with "topic0")
    retired   <- o .: "retired"
    generated <- o .: "generatedFrom"
    pure RigPins
      { pin_selectors       = selectors
      , pin_topics          = topics
      -- Underscore-prefixed keys in the retired block are METADATA (the generator writes a
      -- @_note@ explaining that retired values are not live pins). Dropping them here means a
      -- consumer iterating 'pin_retired' sees retired VALUES only and cannot mistake the note
      -- for one.
      , pin_retired         = Map.filterWithKey (\k _ -> not ("_" `T.isPrefixOf` k)) retired
      , pins_generated_from = generated
      }

instance FromJSON RigAccounts where
  parseJSON = withObject "accounts" $ \o ->
    RigAccounts <$> o .: "deployer" <*> o .: "sender"

instance FromJSON RigPool where
  parseJSON = withObject "pool" $ \o ->
    RigPool
      <$> o .: "poolId"
      <*> o .: "currency0"
      <*> o .: "currency1"
      <*> o .: "tickSpacing"

instance FromJSON RigSeed where
  parseJSON = withObject "seed" $ \o ->
    RigSeed <$> o .: "initTs" <*> o .: "initTick"

instance FromJSON RigAddresses where
  parseJSON = withObject "rig-manifest.json" $ \o ->
    RigAddresses
      <$> o .: "chainId"
      <*> o .: "generatedAt"
      <*> o .: "generatedFrom"
      <*> o .: "accounts"
      <*> o .: "contracts"
      <*> o .: "pool"
      <*> o .: "seed"

-- ---------------------------------------------------------------------------------------------
-- Path resolution
-- ---------------------------------------------------------------------------------------------

-- | @RIG_PINS@, defaulting to the committed pin file.
rig_pins_path :: IO FilePath
rig_pins_path = fromMaybe default_pins_path <$> lookupEnv "RIG_PINS"

-- | @RIG_MANIFEST@, defaulting to the path @deploy-rig.sh@ writes.
rig_manifest_path :: IO FilePath
rig_manifest_path = fromMaybe default_manifest_path <$> lookupEnv "RIG_MANIFEST"

default_pins_path :: FilePath
default_pins_path = "offchain/rig/rig-pins.json"

default_manifest_path :: FilePath
default_manifest_path = "offchain/rig/rig-manifest.json"

-- ---------------------------------------------------------------------------------------------
-- Loading
-- ---------------------------------------------------------------------------------------------

-- | Load both halves from their resolved paths.
load_rig :: IO Rig
load_rig = do
  pins_file     <- rig_pins_path
  manifest_file <- rig_manifest_path
  load_rig_from pins_file manifest_file

-- | The testable core: load from explicit paths (pins first, manifest second).
load_rig_from :: FilePath -> FilePath -> IO Rig
load_rig_from pins_file manifest_file = do
  pins  <- read_json "static pin file" "RIG_PINS" pins_file
  addrs <- read_json "rig address manifest" "RIG_MANIFEST" manifest_file
  case missing_contracts addrs of
    []      -> pure Rig { rig_pins = pins, rig_addrs = addrs }
    missing -> fail (incomplete_message manifest_file missing (rig_contracts addrs))

-- | The contract names the rig manifest schema mandates.
--
-- @contracts@ decodes as an open 'Map' on purpose, so a later rig can add a deployment without
-- a Haskell change. That openness costs something, though: aeson alone cannot tell a complete
-- manifest from one missing @VolOrderManagerMod@, because a smaller map is still a valid map.
-- This list restores the loudness at the only place it can live -- a completeness check after
-- decoding. Extra contracts are always accepted; these seven are not optional.
required_contracts :: [Text]
required_contracts =
  [ "VolOrderManagerMod"
  , "RealizedVolatilityMod"
  , "DynamicFeeMod"
  , "DynamicFeeHook"
  , "PoolManager"
  , "PriceSetterHook"
  , "PriceSetterPoolManager"
  ]

missing_contracts :: RigAddresses -> [Text]
missing_contracts addrs =
  filter (\name -> not (Map.member name (rig_contracts addrs))) required_contracts

incomplete_message :: FilePath -> [Text] -> Map Text Text -> String
incomplete_message path missing present =
  intercalate "\n"
    [ "Rig.Manifest: the rig address manifest decoded but is INCOMPLETE."
    , "  resolved path     : " ++ path
    , "  missing contracts : " ++ intercalate ", " (map T.unpack missing)
    , "  present contracts : " ++ intercalate ", " (sort (map T.unpack (Map.keys present)))
    , "  A rig missing one of its contracts is a broken rig, not a rig with a zero address."
    , "  Re-run the deploy:"
    , "      bash offchain/rig/deploy-rig.sh"
    , "  Override the path with the RIG_MANIFEST environment variable."
    ]

read_json :: FromJSON a => String -> String -> FilePath -> IO a
read_json what env_var path = do
  attempt <- try (eitherDecodeFileStrict path)
  case attempt of
    Left err            -> fail (unreadable_message what env_var path err)
    Right (Left detail) -> fail (malformed_message what env_var path detail)
    Right (Right value) -> pure value

-- | "Loud" means loud AND actionable: name the resolved path, the override variable, and the
-- command that produces the file. A message that says only "key not found" sends the next
-- reader on a hunt.
unreadable_message :: String -> String -> FilePath -> IOException -> String
unreadable_message what env_var path err =
  intercalate "\n"
    [ "Rig.Manifest: cannot read the " ++ what ++ "."
    , "  resolved path : " ++ path
    , "  system error  : " ++ show err
    , "  Stand the rig up (this writes the manifest) with:"
    , "      bash offchain/rig/deploy-rig.sh"
    , "  Regenerate the static pins with:"
    , "      bash offchain/rig/generate-pins.sh"
    , "  Override the path with the " ++ env_var ++ " environment variable."
    ]

malformed_message :: String -> String -> FilePath -> String -> String
malformed_message what env_var path detail =
  intercalate "\n"
    [ "Rig.Manifest: the " ++ what ++ " is present but does not decode."
    , "  resolved path : " ++ path
    , "  decode error  : " ++ detail
    , "  Every field is MANDATORY -- there is no default for a missing address, chain id or"
    , "  pin. A file written by an older rig will not silently half-load."
    , "  Re-run:"
    , "      bash offchain/rig/deploy-rig.sh"
    , "      bash offchain/rig/generate-pins.sh"
    , "  Override the path with the " ++ env_var ++ " environment variable."
    ]

-- ---------------------------------------------------------------------------------------------
-- Lookups -- so callers never index a Map by hand
-- ---------------------------------------------------------------------------------------------

-- | Address of a deployed contract by name. 'Left' names the missing key AND lists the keys
-- that ARE present, which is what turns a typo into a one-read fix.
contract_address :: Rig -> Text -> Either String Text
contract_address rig name =
  look_up "contract" name (rig_contracts (rig_addrs rig))

-- | 4-byte selector, as the @0x@-prefixed lowercase hex the pin file carries.
pin_selector :: Rig -> Text -> Either String Text
pin_selector rig name =
  pin_value <$> look_up "selector pin" name (pin_selectors (rig_pins rig))

-- | Event topic0 as an 'Integer', which is how @VolOrder.Decode@ compares topics.
pin_topic0 :: Rig -> Text -> Either String Integer
pin_topic0 rig name = do
  entry <- look_up "topic0 pin" name (pin_topics (rig_pins rig))
  hex_to_integer name (pin_value entry)

look_up :: String -> Text -> Map Text a -> Either String a
look_up what name table =
  case Map.lookup name table of
    Just found -> Right found
    Nothing ->
      Left $
        "Rig.Manifest: no " ++ what ++ " named " ++ show (T.unpack name)
          ++ "\n  present keys: "
          ++ intercalate ", " (sort (map T.unpack (Map.keys table)))

hex_to_integer :: Text -> Text -> Either String Integer
hex_to_integer name raw =
  case readHex (T.unpack (fromMaybe raw (T.stripPrefix "0x" raw))) of
    [(n, "")] -> Right n
    _ ->
      Left $
        "Rig.Manifest: the topic0 pin for " ++ show (T.unpack name)
          ++ " is not hex: " ++ show (T.unpack raw)
